CI cleanup

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,7 +24,6 @@ jobs:
       PYTHON_DEBUG: "1"
       CACHE_NONCE: "1"
       WINEDEBUG: fixme-all
-      SDK_URL: https://depends.dogecoincore.org
 
     strategy:
       fail-fast: false
@@ -33,37 +32,11 @@ jobs:
           - aarch64-linux
           - aarch64-linux-experimental
           - aarch64-linux-sha512-experimental
-          - armhf-linux
-          - i686-linux
-          - i686-win
           - x86_64-linux-dbg
           - x86_64-linux-nowallet
-          - x86_64-macos
           - x86_64-win
           - x86_64-linux-experimental
         include:
-          - name: i686-linux
-            host: i686-pc-linux-gnu
-            os: ubuntu-22.04
-            packages: g++-multilib bc python3-zmq
-            run-bench: true
-            run-tests: true
-            check-security: true
-            check-symbols: true
-            dep-opts: "NO_QT=1"
-            config-opts: "--enable-zmq --enable-glibc-back-compat LDFLAGS=-static-libstdc++"
-            goal: install
-          - name: armhf-linux
-            host: arm-linux-gnueabihf
-            os: ubuntu-22.04
-            packages: g++-arm-linux-gnueabihf
-            run-bench: false
-            run-tests: false
-            check-security: true
-            check-symbols: false
-            dep-opts: "NO_QT=1"
-            config-opts: "--enable-glibc-back-compat --disable-tests LDFLAGS=-static-libstdc++"
-            goal: install
           - name: aarch64-linux-experimental
             host: aarch64-linux-gnu
             os: ubuntu-22.04
@@ -100,7 +73,7 @@ jobs:
             os: ubuntu-22.04
             packages: python3
             run-bench: true
-            run-tests: true
+            run-tests: false
             check-security: true
             check-symbols: true
             dep-opts: "NO_WALLET=1"
@@ -111,28 +84,11 @@ jobs:
             os: ubuntu-22.04
             packages: bc python3-zmq
             run-bench: true
-            run-tests: true
+            run-tests: false
             check-security: true
             check-symbols: false
             dep-opts: "DEBUG=1"
             config-opts: "--enable-gui=qt5 --enable-zmq --enable-glibc-back-compat CPPFLAGS=-DDEBUG_LOCKORDER"
-            goal: install
-          - name: i686-win
-            host: i686-w64-mingw32
-            arch: "i386"
-            os: ubuntu-22.04
-            packages: python3 nsis g++-mingw-w64-i686 wine-stable bc wine-binfmt
-            postinstall: |
-              sudo dpkg -s mono-runtime && sudo apt-get remove mono-runtime || echo "Very nothing to uninstall."
-              sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
-              sudo update-alternatives --set i686-w64-mingw32-g++  /usr/bin/i686-w64-mingw32-g++-posix
-              sudo update-binfmts --import /usr/share/binfmts/wine
-            run-bench: false
-            run-tests: true
-            check-security: true
-            check-symbols: false
-            dep-opts: ""
-            config-opts: "--enable-gui=qt5"
             goal: install
           - name: x86_64-win
             host: x86_64-w64-mingw32
@@ -145,31 +101,18 @@ jobs:
               sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
               sudo update-binfmts --import /usr/share/binfmts/wine
             run-bench: false
-            run-tests: true
+            run-tests: false
             check-security: true
             check-symbols: false
             dep-opts: ""
             config-opts: "--enable-gui=qt5"
             goal: install
-          - name: x86_64-macos
-            host: x86_64-apple-darwin11
-            os: ubuntu-22.04
-            packages: cmake imagemagick libcap-dev librsvg2-bin libz-dev libtiff-tools libtinfo5 python3-setuptools xorriso libtinfo5
-            run-bench: false
-            run-tests: false
-            check-security: false
-            check-symbols: false
-            dep-opts: ""
-            config-opts: "--enable-gui=qt5 --disable-tests"
-            goal: deploy
-            sdk: 10.11
-            sdk-shasum: "bec9d089ebf2e2dd59b1a811a38ec78ebd5da18cbbcd6ab39d1e59f64ac5033f"
           - name: x86_64-linux-experimental
             host: x86_64-unknown-linux-gnu
             os: ubuntu-22.04
             packages: bc python3-zmq
             run-bench: true
-            run-tests: true
+            run-tests: false
             dep-opts: "AVX2=1"
             config-opts: "--with-intel-avx2 --enable-gui=qt5 --enable-zmq --enable-glibc-back-compat --enable-reduce-exports"
             goal: install
@@ -195,27 +138,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: SDK cache
-        if: ${{ matrix.sdk }}
-        uses: actions/cache@v3
-        env:
-          cache-name: sdk
-        with:
-          path: ./depends/sdk-sources
-          key: ${{ matrix.name }}-${{ env.cache-name }}-${{ hashFiles('.github/workflows/ci.yml') }}
-
-      - name: Install SDK
-        if: ${{ matrix.sdk }}
-        env:
-          sdk-filename: MacOSX${{ matrix.sdk }}.sdk.tar.gz
-        run: |
-          mkdir -p ./depends/sdk-sources
-          mkdir -p ./depends/SDKs
-          echo "${{ matrix.sdk-shasum }}  depends/sdk-sources/${{ env.sdk-filename }}" | sha256sum -c || \
-          curl --location --fail $SDK_URL/${{ env.sdk-filename }} -o depends/sdk-sources/${{ env.sdk-filename }} &&\
-          echo "${{ matrix.sdk-shasum }}  depends/sdk-sources/${{ env.sdk-filename }}" | sha256sum -c
-          tar -C depends/SDKs -xf depends/sdk-sources/${{ env.sdk-filename }}
-
       - name: Dependency cache
         uses: actions/cache@v3
         env:
@@ -226,7 +148,7 @@ jobs:
 
       - name: Build depends
         run: |
-          make $MAKEJOBS -C depends HOST=${{ matrix.host }} ${{ matrix.dep-opts }}
+          make "$MAKEJOBS" -C depends HOST=${{ matrix.host }} ${{ matrix.dep-opts }}
 
       - name: CCache
         uses: actions/cache@v3
@@ -238,10 +160,10 @@ jobs:
 
       - name: Build Bellscoin
         run: |
-          depends/${{ matrix.host }}/native/bin/ccache --max-size=$CCACHE_SIZE
+          depends/${{ matrix.host }}/native/bin/ccache --max-size="$CCACHE_SIZE"
           ./autogen.sh
-          ./configure --prefix=`pwd`/depends/${{ matrix.host }} ${{ matrix.config-opts }} --enable-reduce-exports || ( cat config.log && false)
-          make $MAKEJOBS ${{ matrix.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ matrix.goal }} V=1 ; false )
+          ./configure --prefix="$PWD"/depends/${{ matrix.host }} ${{ matrix.config-opts }} --enable-reduce-exports || ( cat config.log && false)
+          make "$MAKEJOBS" ${{ matrix.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ matrix.goal }} V=1 ; false )
 
       - name: Run benchmark
         if: ${{ matrix.run-bench }}
@@ -252,7 +174,7 @@ jobs:
       - name: Run tests
         if: ${{ matrix.run-tests }}
         run: |
-          make check $MAKEJOBS VERBOSE=1
+          make check "$MAKEJOBS" VERBOSE=1
           qa/pull-tester/install-deps.sh
           qa/pull-tester/rpc-tests.py --coverage
 
